apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtfutfuytcuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtfutfuytcuy
  template:
    metadata:
      labels:
        app: dtfutfuytcuy
    spec:
      containers:
      - image: okteto.dev/dtfutfuytcuy:latest
        name: dtfutfuytcuy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f692c568-5e18-f4b9-a643-a047bb20dffd"
        - name: Vless_Path
          value: "/vdfsdgsfdl555"
        - name: Vmess_UUID
          value: "f692c568-5e18-f4b9-a643-a047bb20dffd"
        - name: Vmess_Path
          value: "/vmgdfgf666"
        - name: Share_Path
          value: "/v2link"
